### ISSUE TITLE
Duplicate Helm chart confusion

### ISSUE THREAD

**Issue by hostalp** [rkosegi/cert-manager-webhook-active24#116]
Currently, there are 2 Helm charts:
- **chart**
Uses older image `rkosegi/cert-manager-webhook-active24:1.0.0`
- **deploy/chart**
Uses newer but currently non-existent image `ghcr.io/rkosegi/cert-manager-webhook-active24:1.0.1` (the right one would be `ghcr.io/rkosegi/cert-manager-webhook-active24:v1.0.1`)
Has an additional `ClusterRole` and `ClusterRoleBinding` in `rbac.yaml`

In the main README.md file, the 2nd one is used in the installation description so I'm not sure what the 1st one is for.
I use that 2nd one with fixed image tag.

In any case, please sort this out so that there's just 1 Helm chart and that it works without any additional modifications.

**Comment by rkosegi** [comment]
Hi @hostalp, thank you for bug report.
I hope this mess was cleaned up in b42f3d6ff4be73c15a1dc9dd6016ab9c920325ac
