### ISSUE TITLE
Failed to pull image "rkosegi/cert-manager-webhook-active24:v1.0.2": reading manifest v1.0.2 in docker.io/rkosegi/cert-manager-webhook-active24: requested access to the resource is denied

### ISSUE THREAD

**Issue by nakladalm** [rkosegi/cert-manager-webhook-active24#145]
Hello, 
Image in docker.hub is not published. 

![Screenshot from 2024-01-02 10-55-15](https://github.com/rkosegi/cert-manager-webhook-active24/assets/126694343/3fb05cf7-dd86-4c7d-86fb-68019da11a1b)

**After download source and run helm upgrade --install ac24 ./chart --namespace cert-manager**

**EVENT K8s:**

ac24-cert-manager-webhook-active24-6874bd4c86-nqpqt.17a67eefb0038230
Failed
Error: ErrImagePull

--

Failed to pull image "**rkosegi/cert-manager-webhook-active24:v1.0.2**": reading manifest v1.0.2 in docker.io/rkosegi/cert-manager-webhook-active24: requested access to the resource is denied

--

Back-off pulling image "rkosegi/cert-manager-webhook-active24:v1.0.2"

**Comment by rkosegi** [comment]
Hi, thanks for report.
I no longer use dockerhub, image is available from [ghcr.io](https://github.com/rkosegi/cert-manager-webhook-active24/pkgs/container/cert-manager-webhook-active24).
As a workaround just add prefix in values.yaml

**Comment by nakladalm** [comment]
Thank you, I'll try it.
